inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  Exclude:
    - node_modules/**/*
    - public/**/*
    - vendor/**/*
    - infra/**/*
    - db/schema.rb
    - spec/{spec,rails}_helper.rb
    - spec/support/**/*
    - Guardfile

Rails:
  Enabled: true # enable rubocop-rails cops
RSpec:
  Enabled: true # enable rubocop-rspec cops
