version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 11032:5432
    volumes:
      - db-data:/var/lib/postgresql/data:cached

  app: &app_base
    tty: true
    stdin_open: true
    environment:
      - ALLOWED_HOST=["localhost:3000"]
      - RAPID_API_KEY=ebfec3a983msh54fe942127aa33ap132dc1jsn98a8f031e8a5
    command: ./scripting_files/web_app_start.sh
    volumes:
      - .:/app:delegated
      - /app/tmp
      - bundle-data:/usr/local/bundle
    ports:
      - 3010:3000

  builder:
    <<: *app_base
    environment:
      - DB_HOST=db
      - DB_USER_NAME=postgres
      - DB_PASSWORD=
    build:
      context: .
      target: basebuilder
    command: ''
    ports: []
volumes:
  db-data:
    driver: local
  bundle-data:
    driver: local
