version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 11032:5432
    volumes:
      - db-data:/var/lib/postgresql/data:cached

  app: &app_base
    tty: true
    stdin_open: true
    environment:
      - ALLOWED_HOST=["localhost:3000"]
      - RAPID_API_KEY=
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - SIDEKIQ_MAX_THREADS=5
      - SIDEKIQ_STDOUT="true"
      - SIDEKIQ_PID=/tmp/sidekiq.pid
    command: ./scripting_files/web_app_start.sh
    depends_on:
      - db
      - redis
    volumes:
      - .:/app:delegated
      - /app/tmp
      - bundle-data:/usr/local/bundle
    ports:
      - 3010:3000

  worker:
    <<: *app_base
    build: .
    environment:
      - DB_HOST=db
      - DB_USER_NAME=postgres
      - DB_PASSWORD=
      - ALLOWED_HOST=["localhost:3000"]
      - RAPID_API_KEY=
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - SIDEKIQ_MAX_THREADS=5
      - SIDEKIQ_STDOUT="true"
      - SIDEKIQ_PID=/tmp/sidekiq.pid
    command: bundle exec sidekiq -C config/sidekiq.yml
    entrypoint: wait-for-it db:5432 -t 30 -s --
    ports: []
    depends_on:
      - db
      - redis
    volumes:
      - .:/app:delegated
      - bundle-data:/usr/local/bundle

  builder:
    <<: *app_base
    environment:
      - DB_HOST=db
      - DB_USER_NAME=postgres
      - DB_PASSWORD=
    build:
      context: .
      target: basebuilder
    command: ''
    ports: []
volumes:
  db-data:
    driver: local
  bundle-data:
    driver: local
