version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db-data:/var/lib/postgresql/data:cached

  app: &app_base
    tty: true
    stdin_open: true
    command: ./scripting_files/web_app_start.sh
    volumes:
      - .:/app:delegated
      - /app/tmp
      - bundle-data:/usr/local/bundle
    ports:
      - 3000:3000

  builder:
    <<: *app_base
    build:
      context: .
      target: basebuilder
    command: ''
    ports: []
volumes:
  db-data:
    driver: local
  bundle-data:
    driver: local
