version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  app: &app_base
    environment:
      - DB_HOST=db
      - DB_USER_NAME=postgres
      - DB_PASSWORD=
    build: .
    depends_on:
      - db
    entrypoint: wait-for-it db:5432 -t 30 -s --

  redis:
    image: redis:7.2-alpine
